
///SIGN IN ACTIONS
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN_LOGOUT = 'SIGNIN_LOGOUT';
export const SIGNIN_OPEN = 'SIGNIN_OPEN';
export const SIGNIN_AUTH_STATE_CHECKED = 'SIGNIN_AUTH_STATE_CHECKED';

///SIGN UP ACTIONS
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_OPEN = 'SIGNUP_OPEN';
export const SIGNUP_ON_BOARDING_GET_STARTED = 'SIGNUP_ON_BOARDING_GET_STARTED';
export const SIGNUP_CHANGE_EMAIL = 'SIGNUP_CHANGE_EMAIL';
export const SIGNUP_CONFIRM_EMAIL_START = 'SIGNUP_CONFIRM_EMAIL_START';
export const SIGNUP_CONFIRM_EMAIL_FAILED = 'SIGNUP_CONFIRM_EMAIL_FAIL';
export const SIGNUP_CONFIRM_EMAIL_SUCCEED = 'SIGNUP_CONFIRM_EMAIL_SUCCEED';
export const SIGNUP_RESEND_EMAIL_CODE = 'SIGNUP_RESEND_EMAIL_CODE';
export const SIGNUP_RESEND_EMAIL_CODE_FAILED = 'SIGNUP_RESEND_EMAIL_CODE_FAILED';
export const SIGNUP_HANDLE_NEXT_VALIDATION_STEP = 'SIGNUP_HANDLE_NEXT_VALIDATION_STEP';
export const SIGNUP_AUTHENTICATION_FAILED = 'SIGNUP_AUTHENTICATION_FAILED';
export const SIGNUP_ADD_PHONE_START = 'SIGNUP_ADD_PHONE_START';
export const SIGNUP_ADD_PHONE_FAILED = 'SIGNUP_ADD_PHONE_FAILED';
export const SIGNUP_ADD_PHONE_SUCCEED = 'SIGNUP_ADD_PHONE_SUCCEED';
export const SIGNUP_CHANGE_PHONE_NUMBER = 'SIGNUP_CHANGE_PHONE_NUMBER';
export const SIGNUP_RESEND_PHONE_CODE = 'SIGNUP_RESEND_PHONE_CODE';
export const SIGNUP_RESEND_PHONE_CODE_FAILED = 'SIGNUP_RESEND_PHONE_CODE_FAILED';
export const SIGNUP_VALIDATE_PHONE_START = 'SIGNUP_VALIDATE_PHONE_START';
export const SIGNUP_VALIDATE_PHONE_FAILED = 'SIGNUP_VALIDATE_PHONE_FAILED';
export const SIGNUP_VALIDATE_PHONE_SUCCEED = 'SIGNUP_VALIDATE_PHONE_SUCCEED';
export const SIGNUP_ON_BOARDING_ENDED = 'SIGNUP_ON_BOARDING_ENDED'
export const SIGNUP_CLOSE_ON_ENDED_DIALOG = 'SIGNUP_CLOSE_ON_ENDED_DIALOG'


///ACCOUNT ACTIONS
export const ACCOUNT_FETCH_INFO_START = 'ACCOUNT_FETCH_INFO_START'
export const ACCOUNT_FETCH_INFO_FAILED = 'ACCOUNT_FETCH_INFO_FAILED'
export const ACCOUNT_FETCH_INFO_SUCCEED = 'ACCOUNT_FETCH_INFO_SUCCEED'

export const ACCOUNT_OPEN_PHONE_VALIDATION = 'ACCOUNT_OPEN_PHONE_VALIDATION'
export const ACCOUNT_PHONE_CODE_SENT = 'ACCOUNT_PHONE_CODE_SENT'
export const ACCOUNT_PHONE_VALIDATION_START = 'ACCOUNT_PHONE_VALIDATION_START'
export const ACCOUNT_PHONE_VALIDATION_SUCCEED = 'ACCOUNT_PHONE_VALIDATION_SUCCEED'
export const ACCOUNT_PHONE_VALIDATION_FAILED = 'ACCOUNT_PHONE_VALIDATION_FAILED'


///EXPLORE PAGE ACTIONS
export const EXPLORE_FETCH_INFO_START = 'EXPLORE_FETCH_INFO_START'
export const EXPLORE_FETCH_INFO_FAILED = 'EXPLORE_FETCH_INFO_FAILED'
export const EXPLORE_FETCH_INFO_SUCCESS = 'EXPLORE_FETCH_INFO_SUCCESS'