
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN_LOGOUT = 'SIGNIN_LOGOUT';
export const SIGNIN_OPEN = 'SIGNIN_OPEN';
export const SIGNIN_AUTH_STATE_CHECKED = 'SIGNIN_AUTH_STATE_CHECKED';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_OPEN = 'SIGNUP_OPEN';
export const SIGNUP_ON_BOARDING_GET_STARTED = 'SIGNUP_ON_BOARDING_GET_STARTED';
export const SIGNUP_CHANGE_EMAIL = 'SIGNUP_CHANGE_EMAIL';
export const SIGNUP_CONFIRM_EMAIL_START = 'SIGNUP_CONFIRM_EMAIL_START';
export const SIGNUP_CONFIRM_EMAIL_FAILED = 'SIGNUP_CONFIRM_EMAIL_FAIL';
export const SIGNUP_CONFIRM_EMAIL_SUCCEED = 'SIGNUP_CONFIRM_EMAIL_SUCCEED';
export const SIGNUP_RESEND_EMAIL_CODE = 'SIGNUP_RESEND_EMAIL_CODE';
export const SIGNUP_RESEND_EMAIL_CODE_FAILED = 'SIGNUP_RESEND_EMAIL_CODE_FAILED';
export const SIGNUP_HANDLE_NEXT_VALIDATION_STEP = 'SIGNUP_HANDLE_NEXT_VALIDATION_STEP';
export const SIGNUP_AUTHENTICATION_FAILED = 'SIGNUP_AUTHENTICATION_FAILED';
export const SIGNUP_ADD_PHONE_START = 'SIGNUP_ADD_PHONE_START';
export const SIGNUP_ADD_PHONE_FAILED = 'SIGNUP_ADD_PHONE_FAILED';
export const SIGNUP_ADD_PHONE_SUCCEED = 'SIGNUP_ADD_PHONE_SUCCEED';
export const SIGNUP_CHANGE_PHONE_NUMBER = 'SIGNUP_CHANGE_PHONE_NUMBER';
export const SIGNUP_RESEND_PHONE_CODE = 'SIGNUP_RESEND_PHONE_CODE';
export const SIGNUP_RESEND_PHONE_CODE_FAILED = 'SIGNUP_RESEND_PHONE_CODE_FAILED';
export const SIGNUP_VALIDATE_PHONE_START = 'SIGNUP_VALIDATE_PHONE_START';
export const SIGNUP_VALIDATE_PHONE_FAILED = 'SIGNUP_VALIDATE_PHONE_FAILED';
export const SIGNUP_VALIDATE_PHONE_SUCCEED = 'SIGNUP_VALIDATE_PHONE_SUCCEED';
export const SIGNUP_ON_BOARDING_ENDED = 'SIGNUP_ON_BOARDING_ENDED'
export const SIGNUP_CLOSE_ON_ENDED_DIALOG = 'SIGNUP_CLOSE_ON_ENDED_DIALOG'

